# categories:
#   - title: ":boom: Breaking Changes"
#     label: "breaking"
#   - title: ":rocket: Features"
#     label: "enhancement"
#   - title: ":fire: Removals and Deprecations"
#     label: "removal"
#   - title: ":beetle: Fixes"
#     label: "bug"
#   - title: ":racehorse: Performance"
#     label: "performance"
#   - title: ":rotating_light: Testing"
#     label: "testing"
#   - title: ":construction_worker: Continuous Integration"
#     label: "ci"
#   - title: ":books: Documentation"
#     label: "documentation"
#   - title: ":hammer: Refactoring"
#     label: "refactoring"
#   - title: ":lipstick: Style"
#     label: "style"
#   - title: ":package: Dependencies"
#     labels:
#       - "dependencies"
#       - "build"
# template: |
#   ## Changes

#   $CHANGES
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  ## [v$NEXT_PATCH_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION)
  ### What's Changed

  _Describe the changes here_

  $CHANGES

change-template: "- $TITLE ([#$NUMBER]($URL)"
category-template: "### $TITLE"

categories:
  - title: Added
    labels:
      - "changelog:added"
  - title: Changed
    labels:
      - "changelog:changed"
  - title: Deprecated
    labels:
      - "changelog:deprecated "
  - title: Removed
    labels:
      - "changelog:removed"
  - title: Fixed
    labels:
      - "changelog:fixed"
  - title: Security
    labels:
      - security
      - changelog:security
  - title: "Dependency Updates"
    labels:
      - dependencies

# version-resolver:
#   major:
#     labels:
#       - "changelog:removed"
#   minor:
#     labels:
#       - "changelog:added"
#       - "changelog:deprecated"
#   patch:
#     labels:
#       - "changelog:fixed"
#       - "changelog:security"
#       - "dependency"

exclude-labels:
  - "skip-changelog"
