# .readthedocs.yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre-build:
      - sphinx-apidoc -o ./api-reference ../../src
sphinx:
  configuration: docs/source/conf.py
formats: all
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
