name: Labeler_manual

# on:
#   push:
#     branches:
#       - main
#       - master

on: workflow_dispatch

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.0.0
        with:
          skip-delete: true
          # yaml-file: .github/labels.yaml
          yaml-file: .github/changelog-labels.yaml
